### ISSUE TITLE
Failing to get nuget from correct source during update

### ISSUE THREAD

**Issue by tsibelman** [fsprojects/Paket.VisualStudio#101]
In my paket.dependencies I have following:

source http://build1:8091/nuget
source https://www.nuget.org/api/v2/

framework: net451
redirects: on

nuget Newtonsoft.Json ~> 8.0 >= 8.0.2

When I trying to update it from visual studio I get following error

Could not resolve package Newtonsoft.Json:
- Dependencies file requested: >= 8.0.2 < 9.0
- Available versions:
  - (7.0.1, [http://build1:8091/nuget])
  - (5.0.8, [http://build1:8091/nuget])

For some reason it searching only in my custom nuget server build1:8091
When I run paket update from command line it works fine.

I using latest version for both tools

**Comment by forki** [comment]
Can you please run "paket clear-cache" and try again?

**Comment by tsibelman** [comment]
Yes it worked. But why is behaved differently for command line ?

**Comment by forki** [comment]
I have no idea. Should have done the same thing.

**Comment by tsibelman** [comment]
Where cache is stored ?

**Comment by forki** [comment]
In the same folder as nuget.
