### ISSUE TITLE
v 0.15.4 from vs gallery locks up vs 2015.1+ when ever I text edit a paket.dependency file

### ISSUE THREAD

**Issue by sillyotter** [fsprojects/Paket.VisualStudio#106]
Just received an update to Paket.Visualstudio through the extension update service.  0.15.4.  Every time I try to edit a paket.dependency file, vs locks up and I have to kill the process.  

Not sure what information would help diagnose this.  Win10EE, VS2015.1 with all updates installed as of this morning.

**Comment by forki** [comment]
shit. It's probably related to https://github.com/fsprojects/Paket.VisualStudio/issues/105

can you describe what I have to do to reproduce?

**Comment by forki** [comment]
looks like I can reproduce

**Comment by forki** [comment]
fixed in 0.15.5

**Comment by sillyotter** [comment]
That fixed it.  Thanks
