### ISSUE TITLE
Paket MUST check (and probably update) paket.lock when you open VisualStudio after paket.dependencies changes (on source control)

### ISSUE THREAD

**Issue by tebeco** [fsprojects/Paket.VisualStudio#113]
### Description

Open a project with changes on Paket.dependencies does not impact paket.lock
The Idea should be :
When you get the Latest source control version, open it and rebuild it (the solution).
You should be using the "dependencies" version, even if it means updation paket.lock
(see repro step)
### Repro steps

Please provide the steps required to reproduce the problem
1. Create a solution that use paket and where paket.dependencies have something like :
   `nuget MyLib 1.0`
   > paket install

The paket.lock is created, Build your solution and the close Visual Studio
2. To simulation a change on SourceControl open your "paket.dependencies" and change it :
`nuget MyLib 2.0`
1. Re open your solution in Visual Studio Try to rebuild all ...
   You'll see that "paket.lock" did not took the v2.0 of the lib but is still using 1.0
   But paket.dependencies indicate v2.0
### Expected behavior

Please provide a description of the behavior you expect.
### Known workarounds

Force "Install manually" when you open the solution (it's a bit f**\* up right ?)
### Related information
- Operating system : Win10
- Release 3.1.9
- Lastest Vs Extension also
- .NET Framework 4.5.x

**Comment by cdrnet** [comment]
I disagree with this view. The source of truth is the lock file, not the dependencies file (that's why the lock file is always checked into source control). The dependencies file is only used to constrain updating the lock file, but such updating is always an explicit action. I would consider it as a hard bug if opening a solution would have the side effect of changing my paket.lock file.

**Comment by forki** [comment]
Restore will never update the lock file. That would violate the idea of the lock file.

**Comment by tebeco** [comment]
So ... you change dependencies then it changes ... another file (the lock)
And the thing you changes has NO MEANING and you have to push the other thing that has been changed in background

So when you fetch you're just hoping that this has been updated ?

Then when you open it does it still sounds logic that Paket does not warn that "dependencies" does not match "lock" ... at least when you open the solution.

I get you're point when you're stuck developping in console mode
But at least the fact that nuget does not have this lock file ensure us to have valid version of package.

And if i'm not wrong, it means that Build Engine/agent should work with paket restore and not paket install ?

If a suggestion magically appears when we open Visual Studio saying "hey do you wan to align lock & dependencies" what do you think ? With a toggle feature in the vs tools options.
So you can keep your actual workflow but at least let developpers be warned if they want.

**Comment by isaacabraham** [comment]
@tebeco - after you update the dependencies file, you need to call `paket update` (or `paket install`) to update the lock file. As @cdrnet rightly says - the lock file is the file that controls the dependencies. The dependencies file is only used as the arguments to _generate_ the lock file.

**Comment by forki** [comment]
duplicat of https://github.com/fsprojects/Paket/issues/1750

**Comment by tebeco** [comment]
That's why I opened the Issue here instead of Paket.
I mean Visual Studio is an IDE and should be oriented to helps you.
This check when you open the solution should be an option you can enable/disable ...

Just like Nuget allready does.
The mean idea is :
- There's always be someone that will forget to update the lock on the Remote repo
- You have better thing to do when you open a solution than "Right click > Install" because you fear that someone forgot this lock file

At least Let the developper decide the behavior, it's an IDE, it's here to provide helps & tips
I mean ... why did you create this extension ? right click > install ? why ? you have command line !!
Then why not notify the user something is allready wrong ?

**Comment by isaacabraham** [comment]
@tebeco the lock file is committed into source control - so you can't get it "out of sync" with another developer.

Don't get confused with the lock file like .NET Core uses - that's not a typical lock file (like every other package manager uses).

**Comment by isaacabraham** [comment]
@tebeco The reason this is closed is because we don't want to build specific logic into the IDE. All the behaviour like this would go into Paket core and then it can be surfaced by any IDE.

**Comment by tebeco** [comment]
@isaacabraham so when you just cross your finger that nobody forget the file ?

We're in the Vs Extension repo right ?

I'm just proposing a feature that will prompt when you open a solution saying "You're lock file differ from your dependencies, do you want to run a paket install ?"
"Yes" / "No"

Clicking "no" will lets thing as they are today, and there's NOTHING related to a build ... so the Build engine is not affected

Click "yes" would only run "paket install" so only the developper will have this prompt and not the build engine

The build engine build without opening the IDE, so this kind of feature does not affect anything about that

**Comment by tebeco** [comment]
@forki And no it's not a duplicate ;)
One is here to let the IDE does stuff for you (the feature in the extension)
The Other one may be here for the command line of paket about sync issue between deps & lock

**Comment by isaacabraham** [comment]
@tebeco What you're proposing is like someone saying that every time you download a project from git it should check that someone didn't forget to merge everything in from a previous commit or something.

Yes, maybe a command to check if lock + dependencies are out of sync - but it shouldn't (IMHO) be part of restore / install stuff.

**Comment by tebeco** [comment]
At least when you open the solution, not every build etc ...
For few years now IDE & tools try to enhance using tips etc ... to give you hint about what's going to goes wrong

I get that we should not alterate the actual behavior of restore or install
But if each time you open a solution you have to either Check version or force install manually, it's time consuming and probably for nothing until someone does a mistake

**Comment by isaacabraham** [comment]
@tebeco what mistake exactly?

**Comment by tebeco** [comment]
I mean, the more you have dev in teams, the more chance you have that someone forget to regenerate (and then push) the lock file.

This is why i'm proposing this feature since it's happening times to times in differents projects here

**Comment by isaacabraham** [comment]
OK, understood. But this is an education issue then, it's a feature of Paket workflow.

It's like saying if you forget to put a try catch around some code and then are surprised when you get an uncaught exception.

**Comment by isaacabraham** [comment]
Having said - if you submit a PR to the core Paket project for a new command whether lock and dependencies are out of sync I imagine it'd be accepted.

**Comment by forki** [comment]
@isaacabraham https://github.com/fsprojects/Paket/issues/1750#issuecomment-228088537

**Comment by isaacabraham** [comment]
Even better.
