### ISSUE TITLE
Cache is created at the wrong location

### ISSUE THREAD

**Issue by matthid** [fsprojects/Paket.VisualStudio#117]
### Description

When using the Visual Studio Plugin and the "Paket" solution the cache is created in `src/Paket.Core/nupkgs/` instead of `nupkgs`
### Repro steps

Open the paket solution an build. Notice that paket caches the nupkg files in `src/Paket.Core/nupkgs/`
### Expected behavior

Use `./nupkgs` as specified in `paket.dependencies`
### Actual behavior

`src/Paket.Core/nupkgs/` is used.
### Known workarounds

None

**Comment by forki** [comment]
Is this reproducible with paket itself?

Am 03.09.2016 10:50 schrieb "Matthias Dittrich" notifications@github.com:

**Comment by matthid** [comment]
No idea what `Paket.VisualStudio` is doing but it looks like `Paket.Core` is assuming the "working directory" = "directory `paket.dependencies` is located in". Which is wrong here. So I would say probably yes.

**Comment by matthid** [comment]
I should note that this is mostly just an annoyance for me. I just figured I should report anyway.

**Comment by sergey-tihon** [comment]
Why `paket.dependencies` is not in the root folder?

**Comment by matthid** [comment]
It is

**Comment by matthid** [comment]
Visual Studio output says `"C:\PROJ\Paket\.paket\paket.exe" restore --references-files "C:\PROJ\Paket\src\Paket.Core\paket.references"` was executed...

**Comment by matthid** [comment]
Yep its probably a paket bug

**Comment by matthid** [comment]
See https://github.com/fsprojects/Paket/issues/1910
