### ISSUE TITLE
Workflow question

### ISSUE THREAD

**Issue by The-Futurist** [fsprojects/Paket.VisualStudio#118]
Hi,

I'm not clear on the overall workflow to be used when we have the addd-in installed.

If we have a solution, it has already been 'paketized' and runs and builds fine. Now we need to add another NuGet package as part of some upgrade.

Well should we use NuGet pakage manager in VS to locate and add the paackage or is there some way to add NuGet packages via this Paket add-in?

If we do add a new package using NuGet package manager then after we add it should we then run:

Tools -> Paket Dependencies Manager -> Update all packages? or 
Tools -> Paket Dependencies Manager -> Convert from NuGet ?

Or is there some other way to 'paketize' the solution after adding a new NuGet package?

Also what if we want to remove a NuGet package, again should we run some Paket command?

Thanks

Hugh

**Comment by forki** [comment]
there are add package and remove package context menus

![image](https://cloud.githubusercontent.com/assets/57396/18505658/8e3e2872-7a68-11e6-9509-1bda1521f980.png)
