### ISSUE TITLE
Assembly redirects in app.config do not match to what paket.exe does

### ISSUE THREAD

**Issue by llehn** [fsprojects/Paket.VisualStudio#123]
If I do
paket.exe install
it installs redirects like this:
`<bindingRedirect oldVersion="0.0.0.0-65535.65535.65535.65535" newVersion="4.1.1.0" />`

the VS extenstion uses this (which is what paket.exe used to use)
`<bindingRedirect oldVersion="0.0.0.0-999.999.999.999" newVersion="4.1.1.0" />`

This results in lots of modified files, which is not good.

Permanent solution would be to use paket.exe [as described here](https://github.com/fsprojects/Paket.VisualStudio/issues/73)

Or upgrade paket.core as a short term solution

**Comment by forki** [comment]
Paket.Core updated. Thanks for reporting
