### ISSUE TITLE
VS 2017 RC (aka VS15) not yet supported

### ISSUE THREAD

**Issue by embix** [fsprojects/Paket.VisualStudio#129]
### Description

As there is already an [RC of the Visual F# Sharp Powertools](ttps://twitter.com/FSPowerTools/status/800247828295495680) I working on an FSharp project in VS2017 RC. 

### Repro steps

Please provide the steps required to reproduce the problem

1. Install VS 2017 RC

2. Try installing recent Paket.VisualStudio.vsix.

### Expected behavior

I hoped we already have a VS2017RC compatible version, so I expected the installation to work.

### Actual behavior

 you'll get an "Installation Failed" message. 

Related Log Entries:
    23.12.2016 14:27:13 - Microsoft VSIX Installer
    23.12.2016 14:27:13 - -------------------------------------------
    23.12.2016 14:27:13 - vsixinstaller.exe version:
    23.12.2016 14:27:13 - 15.0.26014.0 built by: D15REL
    23.12.2016 14:27:13 - -------------------------------------------
    23.12.2016 14:27:13 - Command line parameters:
    23.12.2016 14:27:13 - C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\Common7\IDE\VSIXInstaller.exe,C:\Users\Administrator\Desktop\Paket.VisualStudio.vsix
    23.12.2016 14:27:13 - -------------------------------------------
    23.12.2016 14:27:13 - Microsoft VSIX Installer
    23.12.2016 14:27:13 - -------------------------------------------
    23.12.2016 14:27:14 - Initializing Install...
    23.12.2016 14:27:14 - Extension Details...
    23.12.2016 14:27:14 - 	Identifier         : Paket.VisualStudio
    23.12.2016 14:27:14 - 	Name               : Paket for Visual Studio
    23.12.2016 14:27:14 - 	Author             : Igal Tabachnik
    23.12.2016 14:27:14 - 	Version            : 0.30.1
    23.12.2016 14:27:14 - 	Description        : Manage your Paket dependencies from Visual Studio!
    23.12.2016 14:27:14 - 	Locale             : en-US
    23.12.2016 14:27:14 - 	MoreInfoURL        : 
    23.12.2016 14:27:14 - 	InstalledByMSI     : False
    23.12.2016 14:27:14 - 	SupportedFrameworkVersionRange : [4.0,4.5]
    23.12.2016 14:27:14 - 
    23.12.2016 14:27:14 - 	SignatureState     : Unsigned
    23.12.2016 14:27:14 - 	Supported Products : 
    23.12.2016 14:27:14 - 		Microsoft.VisualStudio.Pro
    23.12.2016 14:27:14 - 			Version : [11.0]
    23.12.2016 14:27:14 - 		Microsoft.VisualStudio.Pro
    23.12.2016 14:27:14 - 			Version : [12.0]
    23.12.2016 14:27:14 - 		Microsoft.VisualStudio.Pro
    23.12.2016 14:27:14 - 			Version : [14.0]
    23.12.2016 14:27:14 - 
    23.12.2016 14:27:14 - 	References         : 
    23.12.2016 14:27:14 - 		-------------------------------------------------------
    23.12.2016 14:27:14 - 		Identifier   : Microsoft.VisualStudio.MPF
    23.12.2016 14:27:14 - 		Name         : Visual Studio MPF
    23.12.2016 14:27:14 - 		Version      : [10.0,)
    23.12.2016 14:27:14 - 		MoreInfoURL  : 
    23.12.2016 14:27:14 - 		Nested       : No
    23.12.2016 14:27:14 - 
    23.12.2016 14:27:14 - Signature Details...
    23.12.2016 14:27:14 - 	Extension is not signed.
    23.12.2016 14:27:14 - 
    23.12.2016 14:27:14 - Searching for applicable products...
    23.12.2016 14:27:14 - Found installed product - Global Location
    23.12.2016 14:27:14 - Found installed product - Visual Studio Enterprise 2017 RC
    23.12.2016 14:27:14 - VSIXInstaller.NoApplicableSKUsException: This extension is not installable on any currently installed products.
       at VSIXInstaller.App.GetInstallableData(String vsixPath, Boolean isRepairSupported, IEnumerable`1& skuData)
       at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
       at VSIXInstaller.App.Initialize()
       at System.Threading.Tasks.Task`1.InnerInvoke()
       at System.Threading.Tasks.Task.Execute()

### Known workarounds

I added the following lines to the extension.vsixmanifest

      <VisualStudio Version="15.0">
        <Edition>Pro</Edition>
      </VisualStudio>

and got a Warning that this extension is not compatible with VS15 and it may cause Visual Studio to be unstable. After Accepting, the installation finished. Log was also fine:

    Searching for applicable products...
    Found installed product - Global Location
    Found installed product - Visual Studio Enterprise 2017 RC
    The extension with ID 'Paket.VisualStudio' is not installed to Visual Studio Enterprise 2017 RC.
    The following target products have been selected...
    	Visual Studio Enterprise 2017 RC
    
    Beginning to install extension to Visual Studio Enterprise 2017 RC...
    Install to Visual Studio Enterprise 2017 RC completed successfully.

After that, paket restore in VS worked.

### Related information 

* Operating system: Windows Server 2012 R2 Standard
* Branch: release version of 0.30.1 (vsix from github)
* .NET Runtime Version: 4.6.1

**Comment by villasv** [comment]
Title says VS 2015 RC, everywhere else VS 2017 RC?

**Comment by hmemcpy** [comment]
Fixed :)
