### ISSUE TITLE
Adding package when sources are splitted (command line or UI)

### ISSUE THREAD

**Issue by SuperRoflCopter** [fsprojects/Paket.VisualStudio#137]
I've noticed an issue when adding package to a project via "paket add" command line or "Add Package" interface.

When your dependencies file look like this :

```
source https://www.nuget.org/api/v2/

nuget nuget1
nuget nuget2

source https://InternalRepository

nuget nuget3
```

If you try adding a package from the "InternalRepository" you'll get the following error message :
![image](https://cloud.githubusercontent.com/assets/1961983/23791029/c6f70af4-0581-11e7-970b-a2eecb45aa7c.png)

A possible fix would be to be able to target a specific source, or for the paket add command to add the package at the right place in the dependencies file depending on the source of the package.

..or not splitting the packages by sources.. but it is faster that way. :)

**Comment by forki** [comment]
Do you have a concrete dependencies file + concrete paket add command for
me to repro?

Am 10.03.2017 11:08 vorm. schrieb "ThomasPomme" <notifications@github.com>:

**Comment by SuperRoflCopter** [comment]
You can use this case for example (random public feed) :

```
framework: net451

source https://www.nuget.org/api/v2/

nuget Unity 2.1.505.2
nuget Unity.Interception 2.1.505.2
nuget Newtonsoft.Json 7.0.1

source https://sitecore.myget.org/F/sc-packages/

nuget CRMSecurityProvider
nuget Data-Exchange-Framework
```

Try add this package from https://sitecore.myget.org/F/sc-packages/ repo  : 
Data-Exchange-Framework-Remote-SDK

(paket add nuget Data-Exchange-Framework-Remote-SDK)

And I get the following error :
![image](https://cloud.githubusercontent.com/assets/1961983/23854856/9932014a-07f3-11e7-9664-34a51f4bf7f5.png)

**Comment by SuperRoflCopter** [comment]
Thanks for the quick fix.
Everything seems fine for both (command line and visual studio)
