### ISSUE TITLE
MissingMethodException when running command (Install/Update/Outdated)

### ISSUE THREAD

**Issue by SuperRoflCopter** [fsprojects/Paket.VisualStudio#141]
Hi,
Since the new release of paket 5, we had an issue running the latest branch of Paket.VisualStudio

- Get master branch or solution_restore branch
- Run extension in experimental visual studio
- Right click dependencies file / update

![image](https://user-images.githubusercontent.com/1961983/27637547-67824558-5c10-11e7-858b-f4125dd2e74b.png)

Instead of updating the paket.lock it crash with a _MissingMethodException_ when returning FSharpList

I tried restoring with the actual paket.lock and updating with the latest paket.core nuget. Both resulting with the same error.

Have you got a work around for this issue?

Thanks,
Thomas

**Comment by forki** [comment]
please retry with latest

**Comment by SuperRoflCopter** [comment]
Thanks !
It works indeed. 
Weird thing is I tried on my side with redirect force on FSharp.Core and it did not seem to work better. 
Probably forgot something.

**Comment by SuperRoflCopter** [comment]
I had the same issue while referencing paket.core from a vsix solution,
Even the redirect on FSharp.Core was not fixing the problem. 
Chessie was build with FSharp.Core 4.0.0.0 and was causing the issue.
Finally I had to rebuild Chessie in .Net 4.5 instead of .Net 4.0, then update FSharp.Core with redirect to solve the issue.
