### ISSUE TITLE
clitool error

### ISSUE THREAD

**Issue by davidtme** [fsprojects/Paket.VisualStudio#142]
### Description

Adding `clitool dotnet-fable` into `paket.dependencies` results in `paket.references` throwing errors

![image](https://user-images.githubusercontent.com/1804141/28210108-ba2c54d6-688d-11e7-8a10-1f80e097eaaa.png)

### Related information 

* Visual Studio 15.2
* Packet for Visual Studio 0.32.2

**Comment by forki** [comment]
fixed. but with new csproj/fsproj you shound't use the addin anymoere
the stuff is much better integrated
