### ISSUE TITLE
Cannot locate .paket folder

### ISSUE THREAD

**Issue by BlythMeister** [fsprojects/Paket.VisualStudio#152]
### Description

Since recent update i get build error saying restore failed as the .paket folder cannot be located.
It it looking 1 level too deep for the .paket folder.

### Repro steps

Setup repo as follows:

| .paket
|->| paket.exe
|->| paket.bootstrapper.exe
| src
|->| MyProject
|->|->| MyProject.csproj
|->|->| MyProject.sln
|->| MyOtherProject
|->|->| MyOtherProject.csproj
|->|->| MyOtherProject.sln
|->| MyCombinedSolution.sln

When building from any of the 3 solutions it searches for the .paket folder under the src folder and not at the root of the repo.

### Expected behavior

Paket is found and used

### Actual behavior

packet is not found and errors

### Known workarounds

put the .paket folder under the src folder

### Related information 

The getting started (https://fsprojects.github.io/Paket/getting-started.html) states to create at the root.

**Comment by Yewridge** [comment]
Hi, I've got 0.37.7 installed but am still seeing the above issue.

**Comment by BlythMeister** [comment]
@forki can you re-open this please, i am also still seeing this issue :(

Restoring packages
Could not locate .paket\paket.exe and .paket\paket.bootstrapper.exe under the solution F:\GIT\MyRepo

the .paket folder is under the MyRepo folder

**Comment by forki** [comment]
Please send a pull request

**Comment by BlythMeister** [comment]
i can try ;)

**Comment by forki** [comment]
Thanks

Am 20.10.2017 17:21 schrieb "Chris Blyth" <notifications@github.com>:

**Comment by BlythMeister** [comment]
Tested and this and it now works!
