### ISSUE TITLE
Paket Initialize should take care of downloading the bootstrap if it doesn't exist

### ISSUE THREAD

**Issue by gdennie** [fsprojects/Paket.VisualStudio#159]
### Description

`Paket` must first be manually initialized prior to performing `Initialize Paket` as per the options in the `Tools/Packet Dependencies Manager/Initialize Paket` menu, undermining the very notion of initialization.

### Repro steps

Create a new solution
Select `Tools/Packet Dependencies Manager/Initialize Paket`

### Expected behavior

`Paket` is ready to update, install, remove, and query packages

### Actual behavior

Error: could not locate .paket/paket.exe and .paket/paket.bootstrapper.paket.exe under the folder, `c:\projectSolutionFolder\`

### Known workarounds

go to the command prompt and figure out a way to copy paket.exe into .paket folder in your solution directory. Typically you use curl or git clone the packet repository or copy paket.exe from somewhere else

### Related information 

* Operating system
* Branch
* .NET Runtime Version
* Performance information, links to performance testing scripts

**Comment by gdziadkiewicz** [comment]
@forki Could you close this issue? I failed to use the close issue on pull request merge by keyword feature properly in #162 .
