### ISSUE TITLE
Create nice UI for "Add package"

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket.VisualStudio#33]
At the moment we support the following UI:

![image](https://cloud.githubusercontent.com/assets/57396/7665439/6c9325a6-fbb6-11e4-944b-49a6f5483527.png)

![image](https://cloud.githubusercontent.com/assets/57396/7665442/8ffe110e-fbb6-11e4-828f-dc65aebcff47.png)

this is implemented in https://github.com/fsprojects/Paket.VisualStudio/blob/master/src/Paket.VisualStudio/Commands/AddPackageProcess.cs#L15 and only meant as a prototype.

We'd like to see a nicer version (maybe done with http://reactiveui.net/) which allows really good autocomplete.

Also it would be nice if the output during the add command could be shown in a dialog.

**Comment by TheAngryByrd** [comment]
I can take a swing at it.

**Comment by TheAngryByrd** [comment]
What kind of workflows should the UI allow?

Currently the workflow of the UI is

```
open ui -> search for packages on nuget -> add package only from nuget -> close ui -> add package to paket file
```

How much more like do we want to see this like the nuget package explorer?  

```
open ui -> search for packages -> add packages from nuget -> show output -> repeat until user closes ui
```

**Comment by forki** [comment]
Mhm good question. I think one package is enough. I can't remember when I installed more than one at a time.
