### ISSUE TITLE
build.cmd fails if VS2015 is installed

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket.VisualStudio#44]
it detects wrong VS SDK path and stuff.

@hmemcpy Any ideas?

**Comment by hmemcpy** [comment]
Oh jeez. Got a build log?
Trying now...

**Comment by hmemcpy** [comment]
Works here, I even opened a non-developer command prompt to run it.

**Comment by forki** [comment]
targets file is missing. But it's looking in v.14

**Comment by hmemcpy** [comment]
Hmm, do you have VSSDK 2015 installed? Because you need to.
The reason you're getting this is due to msbuild version -> it's probably
taking the latest it could find, so 14.0

On Tue, May 19, 2015 at 11:45 AM, Steffen Forkmann <notifications@github.com

**Comment by forki** [comment]
Ok where can I get VS2015 sdk?

**Comment by hmemcpy** [comment]
Holy crap, they hidden it well on the VS2015 download page, somewhere in
the bottom in the maze of menus!

Here's the direct link for VS2015 RC SDK:
http://go.microsoft.com/?linkid=9877247

On Tue, May 19, 2015 at 11:47 AM, Steffen Forkmann <notifications@github.com

**Comment by forki** [comment]
cool. thanks that helped.

**Comment by hmemcpy** [comment]
Another day, another yak.

On Tue, May 19, 2015 at 12:13 PM, Steffen Forkmann <notifications@github.com

**Comment by theimowski** [comment]
I had the same problem, and could workaround by changing 

https://github.com/fsprojects/Paket.VisualStudio/blob/master/build.fsx#L103 

to give it extra parameter `["VisualStudioVersion", "12.0"]`

**Comment by forki** [comment]
hey @theimowski, you know how to send PRs... ;-)

**Comment by theimowski** [comment]
yeah my bad, thought it's just me not having VS2015 SDK installed. Hold on a sec
