### ISSUE TITLE
Solution Explorer crashes when startet w/o solution

### ISSUE THREAD

**Issue by Slesa** [fsprojects/Paket.VisualStudio#48]
Starting VStudio 2013 without a solution, the solution explorer does not show anything when loading a solution afterwards.
After disabling the paket addin, it works fine.

**Comment by Slesa** [comment]
In debugging mode, I cannot see anything unusual... maybe there are other extensions interfering?

**Comment by forki** [comment]
yes I was looking into this, but could not reproduce.

**Comment by hmemcpy** [comment]
Sorry, I'm still not near an actual computer...

Could you please run Visual Studio with `devenv.exe /log c:\temp\log.xml`,
then reproduce the problem and attach the log here? Maybe the stacktrace
will be visible.

@forki In any event, it really doesn't make sense for the extension to load
if no solution was loaded, so inside the main package.cs file, try removing
the attribute with NoSolution parameter...

**Comment by forki** [comment]
```
[ProvideAutoLoad(UIContextGuids.SolutionExists)]
[PackageRegistration(UseManagedResourcesOnly = true)]
[InstalledProductRegistration("#110", "#112", "1.0", IconResourceID = 400)]
[ProvideMenuResource("Menus.ctmenu", 1)]
[Guid(Guids.PackageGuid)]
public sealed class PaketPackage : Package
{
}
```

there is no NoSolution

**Comment by hmemcpy** [comment]
Oh, for some reason I thought there was :(

Well, let's hope the log reveals the problem

**Comment by Slesa** [comment]
After disabling and re-enabling Paket.VS, the effect has gone.
I'll try it at home. If it happens again, I will use the devenv parameters to see what is going on.

**Comment by Slesa** [comment]
Cannot reproduce again. Maybe earth radiation.
