### ISSUE TITLE
Add Pakage fails

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket.VisualStudio#51]
In VS2013, clicking Add Package on a dependencies file I get the following error: -

`The calling thread must be STA, because many UI components require this.`.

**Comment by hmemcpy** [comment]
Yikes! I suspect this has to do with Tasks and Synchronization contexts....
need to check...

**Comment by isaacabraham** [comment]
This actually shows up as a red squiggly even in solution explorer.

![Paket VS](https://pbs.twimg.com/media/CFi5l3aVAAAMuRZ.png)

**Comment by forki** [comment]
Wow. Didn't know you can get squiggles in solution Explorer.

**Comment by TheAngryByrd** [comment]
Oh boy.

**Comment by isaacabraham** [comment]
Secret squirrel Productivity Power Tools.

**Comment by hmemcpy** [comment]
Yes! Productivity Power Tools is the extension that can add squigglies...
Did you figure out why that happens?

**Comment by isaacabraham** [comment]
Nope. I'll try removing the extension and seeing if that removes the error.

**Comment by hmemcpy** [comment]
Before you do that, please try running VS with `devenv /log c:\temp\log.xml`, then open the .xml and look for anything "error" in it...

**Comment by TheAngryByrd** [comment]
I figured out the error.  I'll submit a patch soon.

**Comment by forki** [comment]
Any news on this?

**Comment by TheAngryByrd** [comment]
Gonna break this out of what I had and send a separate pull request. I'll get that submitted tonight.

**Comment by forki** [comment]
@isaacabraham did it work for you?

**Comment by isaacabraham** [comment]
Will try tomorrow :)
