### ISSUE TITLE
Make "paket add" available on project nodes 

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket.VisualStudio#54]
Nuget has the add package command available on project nodes in the solution Explorer (and on the "References" node). We should add this too. Especially for new solutions this is important since we don't have paket.references nodes yet

**Comment by hmemcpy** [comment]
Sigh... more vsct hackery.
I'd "borrow" that from nuget:
https://github.com/NuGet/NuGet.VisualStudioExtension/blob/dev/src/VsExtension/NuGetTools.vsct

I'm guessing, add to IDG_VS_CTXT_REFROOT_ADD

On Mon, May 25, 2015 at 11:57 AM, Steffen Forkmann <notifications@github.com

**Comment by forki** [comment]
Thx. That helped
