### ISSUE TITLE
Add package searches from public feed when that source is not in the packages.depenencies

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket.VisualStudio#57]
The UI for Add Packages defers to the public nuget gallery even when that feed isn't in the packages.dependencies for the project in question:

![image](https://cloud.githubusercontent.com/assets/573979/8036636/c0f2cf10-0dbe-11e5-888a-a931c2b1700e.png)
You can see the fiddler logs in this image.

The two feeds for this project are private company feeds, one for internally-produced packages and one for specific approved versions of public packages, so in the ideal case I'd not see Paket.Core in the search results here.

I haven't looked into if the problem is the allowed source list that paket.core is using to do the lookup or if paket.visualstudio is at fault here.

**Comment by forki** [comment]
please try again with Paket.VisualStudio 0.4.2

**Comment by baronfel** [comment]
Awesome, we no longer see the public results, thanks!

We don't see any packages at all, but that's because our hosted Nuget server doesn't support the apiv3 autocomplete.  It'd be nice to fallback to old-style search, but that's outside the scope of this issue.
