### ISSUE TITLE
Type ahead does not work properly in Add package window

### ISSUE THREAD

**Issue by alexeyzimarev** [fsprojects/Paket.VisualStudio#60]
When I use the Add package window, if I am fast and know the package name, I can type it in and see the right results. However, if I type slower, the throttle period is very little, so the list shows packages that match, say, first two letters. The problem is that any further input does not cause the list to refresh. Also, I can remove all text in the search box and enter something else, the list stays the same. The progress indicator is always on, never stops.

**Comment by forki** [comment]
I mark this up-for-grabs since I think it would be a nice start for people to join the project.

**Comment by TheAngryByrd** [comment]
I think this might be a problem upstream with the call into Paket.Core.  Even though I added the OnComplete call, it still never seems to get the OnCompleted signal and the ReactiveCommand never properly "finishes".  So this should be a good place to start looking.

**Comment by alexeyzimarev** [comment]
First, we can increase the throttle to 500 ms instead of 250. Plus, add at least three characters condition in Where.

**Comment by alexeyzimarev** [comment]
I am not an expert in ReactiveUI but I would have used CreateAsyncTask instead of CreateAsyncObservable.

**Comment by ForNeVeR** [comment]
Thank you guys for the clues. It seems that it's a problem with [`Paket.Utils.ObservableExtensions.flatten`](https://github.com/fsprojects/Paket/blob/42a54861073ca74170183309569c79cdca85e40b/src/Paket.Core/Utils.fs#L519-L523) that never called `obs.OnComplete`. I'll send a PR to Paket core to fix that.
