### ISSUE TITLE
Paket for Visual Studio does not use paket.exe from my .paket folder?

### ISSUE THREAD

**Issue by Bananas-Are-Yellow** [fsprojects/Paket.VisualStudio#63]
Hello forki

The [bug](https://github.com/fsprojects/Paket/issues/921#issuecomment-122531732) that you fixed in the Paket project does not seem to be fixed when I use the Visual Studio integration. I updated the `paket.exe` in my `.paket` folder to 1.19.7 (by running `paket.bootstrapper.exe` with no arguments), but when I use the **Check for Updates** command on the context menu, the bug is not fixed and I still get:

```
Couldn't retrieve versions for System.Runtime.WindowsRuntime
```

If instead I open a Command Window in the `.paket` folder and run `packet outdated`, it works fine.

Does the Visual Studio integration not use the `paket.exe` in my `.paket` folder?

**Comment by forki** [comment]
nope. paket.visualstudio uses Paket.core. Let me release a new version.

**Comment by forki** [comment]
done

**Comment by Bananas-Are-Yellow** [comment]
Thanks.
