### ISSUE TITLE
Should restore unload projects like install/update/remove?

### ISSUE THREAD

**Issue by baronfel** [fsprojects/Paket.VisualStudio#64]
Imagine the case where a user has VS open in a solution with a project whose dependencies are managed by Paket. This is a source-controlled project shared between multiple developers.

When developer A updates the project from source control and the changes include a new version of an already-referenced package, it is possible for the restore to fail if Visual Studio has locked any of the files in that package's folder, especially XML documentation.

It would be ideal if we could get VS to stop locking, but I think a more approachable workaround would to be for Paket.VisualStudio to follow the same 'unload-> run task -> reload' flow that it does for install/update/remove.

**Comment by forki** [comment]
yes I assume you are right. PR very welcome

**Comment by baronfel** [comment]
Excellent, I'll see if I can take a stab at it then.
