### ISSUE TITLE
Code completion for paket.references

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket.VisualStudio#66]
It would be awesome if you could get code completion in paket.references which was (list of distinct dependencies listed in paket.lock - existing dependencies in references file). This would make adding new references to existing dependencies easier.

**Comment by forki** [comment]
@Krzysztof-Cieslak do we already have this for atom?

**Comment by Krzysztof-Cieslak** [comment]
Nope, we don't. But it should be easy to add using http://fsprojects.github.io/Paket/paket-show-installed-packages.html - list of completions is a result of this command minus result of command with `project` parameter

**Comment by Krzysztof-Cieslak** [comment]
Or you could add separate operation to Paket, Your call, don't know if it's worth "polluting" Paket with next command.

**Comment by hmemcpy** [comment]
Oh wow, :clap:

**Comment by forki** [comment]
nothing fancy, but seems to work:

![image](https://cloud.githubusercontent.com/assets/57396/9305820/9553e5ca-44f4-11e5-8af2-bc8164a76dd1.png)

**Comment by Krzysztof-Cieslak** [comment]
+309 lines for such simple feature? VS API is so amazing -.-

Just kidding, looks fantastic :)

**Comment by forki** [comment]
Yeah I duplicated all the classes @hmemcpy created. it's called copy paste development (CPD)

**Comment by hmemcpy** [comment]
I prefer Clipboard Inheritance...

**Comment by isaacabraham** [comment]
AKA "code redundancy" - a great idea, because if your source control goes "wrong" and loses one of the files, you'll have the code in the other one.
