### ISSUE TITLE
Use paket.exe instead of Paket.Core 

### ISSUE THREAD

**Issue by forki** [fsprojects/Paket.VisualStudio#73]
This project uses Paket.Core to perform paket operations. This means we always have to create a new Paket.VisualStudio release for every paket release. And even worse: users have to constantly upgrade the addin. 

In atom we use a different way. We always restore the latest paket.exe and use it as a separate process. This works like a Charme.

**Comment by aidapsibr** [comment]
+1

**Comment by jbaehr** [comment]
When you perform this switch, please keep users behind a password-protected corporate proxy in mind. If this extension starts to require unrestricted internet access, it becomes useless for us. And that would be very sad.

**Comment by isaacabraham** [comment]
@jbaehr perhaps it could be bundled with the latest version of the extension - at least that way you are no worse off than now - or have the ability to specify the path to paket.exe?

**Comment by jbaehr** [comment]
I'm fine with both options.

**Comment by llehn** [comment]
+1.
To workaround unrestricted internet access, there could be a setting to force to get paket.exe from nuget. (using a corporate nuget server - with credential support).

**Comment by jbaehr** [comment]
This setting is effectively there already. In `paket.bootstrapper.exe.config` you can specify the `NugetSource` as well as the `PaketVersion`. This is exactly what we need and use via msbuild (`paket.targets`). It would be awesome if the VS extension for paket would use the very same process to acquire `paket.exe`.
Another benefit of using the solution-local `paket.exe` would be some protection against breaking changes. Right now we cannot use the latest version of the extension as this one uses paket-5 internally. Some of our solutions are still depending on paket-4 and at least the `paket.lock` format slightly changed.

**Comment by jbaehr** [comment]
I think this ticket can be closed, right?
