### ISSUE TITLE
Clone "Manage NuGet Packages" behaviour for adding references to projects

### ISSUE THREAD

**Issue by frankshearar** [fsprojects/Paket.VisualStudio#77]
If you right click a project, the "Manage NuGet Packages" dialog will
- let you find a NuGet package
- update the packages.config
- add that package to the project
- (crucially) add that package's dependencies to the project.

I would dearly love to see Paket.VisualStudio provide something similar:
- let me find a package
- add that package & its dependencies to the affected project

**Comment by forki** [comment]
What's wrong with the current "add package" dialog in Paket.VisualStudio?

**Comment by frankshearar** [comment]
"Add package" lets me easily find a package, it's true. But if I want to add a reference to that package _to a project_ I will still have to right-click References, Browse, dig in the file system, add, for that package and its dependencies.

Concrete example: I want to be able to add Chessie to a project, and have the <Reference> tags for Chessie and FSharp.Core automatically added, as well as the necessary binding redirects for the project's app.config.

It's the latter part that's more important than the former: if I had to add a package to the solution in one step, and then had to add the package to the project as a second step, that would still work for me.

**Comment by forki** [comment]
Right click on references file of that project should also give you paket
add with the stuff you described.

**Comment by frankshearar** [comment]
Fabulous! I get an error "The path is not of legal form." though - separate bug report time?

**Comment by forki** [comment]
yes. that sounds like a real issue. please try to give us repro steps in separate issue.
