### ISSUE TITLE
Improve error messages during Add Package

### ISSUE THREAD

**Issue by frankshearar** [fsprojects/Paket.VisualStudio#78]
In #77 @forki pointed me to now Paket.VisualStudio already does what I want it to. But when I tried to "Add Package" on a project, I just got an error "The path is not of a legal form." No idea what path!

I don't know what path, and am going to try a hack locally, where in AddPackageProcess.ShowAddPackageDialog I wrap the construction of the FileInfo in a

```
catch (ArgumentException e)
{
    throw new ArgumentException(e.ToString(), e);
}
```

so I can find out what path is illegal.

**Comment by forki** [comment]
cool. if you find something let me know.

**Comment by frankshearar** [comment]
It's not much, but the selectedFileName == "", which is of course not a legal path.

**Comment by forki** [comment]
Ok. Do you already see a fix? If not, can you describe how I can reproduce?

**Comment by frankshearar** [comment]
I don't see a fix yet. To reproduce, all I'm doing it right-clicking an fsproj in a solution that's always used Paket (but I've only ever driven paket from the command line until now), hitting Add Package, and see the error.

But this is such a common use case there must be something weird going on on my machine. VS 2013 update 3, on a Windows 10 machine.

**Comment by forki** [comment]
i can repro.

**Comment by forki** [comment]
fix is deployed to VS gallary. thanks for reporting
