### ISSUE TITLE
paket.references intellisense doesn't work in VS2015

### ISSUE THREAD

**Issue by isaacabraham** [fsprojects/Paket.VisualStudio#82]
I just get an item "Main" repeated several times, instead of the dependencies in the .dependencies file.

**Comment by forki** [comment]
I guess groups feature broke that. Well shit.
Will look at this on Monday

**Comment by isaacabraham** [comment]
I don't think so. I seem to recall seeing this quite a while ago and hoping it would just go away.

**Comment by forki** [comment]
Maybe I should start to use the plug-in so I can feel the pain ;-)

**Comment by isaacabraham** [comment]
It's not painful, it's great :-) But this is a little bit annoying.

**Comment by forki** [comment]
fixed that.
I now even filters the list of packages according to the group where you start the intellisense process
