### ISSUE TITLE
Add package search not working with Klondike

### ISSUE THREAD

**Issue by pms1969** [fsprojects/Paket.VisualStudio#87]
I'm on a corporate network, and we're evaluating Paket.  This of course includes the VS Extension.  What I've found is that when trying to Add a new package to my project, I cannot from inside VS thru the extension.  The Search window pops up, but I am unable to find anything.  Our internal nuget repo's are all Klondike.

When converting nuget to paket, I've had to set the nuget repo's to .../api/odata in order for it to work properly, and I have no problem with that since it works beautifully after that, but I was wondering if that setup did not play nicely with the extension, of if I have some fundamental misunderstanding of the way it all hangs together.

For reference, update packages and check for updates works just fine.

**Comment by forki** [comment]
mhm. actually I'm not sure if we implemented this. I think we only support nuget.org at the moment, since it's the only API which has v3 autocomplete interface.

**Comment by pms1969** [comment]
ok, just looked at the find-packages command line argument too, and it doesn't look like it's using the sources in the paket.dependencies file either. :-(  If I add the source it doesn't find things I know are in there either.

Any chance of a fix?

**Comment by pms1969** [comment]
By the way, excellent work, it's a great product.

**Comment by forki** [comment]
there is probably some v2 api which lists all packages. /cc @maartenba

**Comment by maartenba** [comment]
/api/v2/Packages, follow continuation tokens.

**Comment by forki** [comment]
is it possible to filter serverside?

**Comment by pms1969** [comment]
http://fakeklondikeserver/api/odata/Packages()?$filter=Id eq 'DotNetZip'

works serverside

**Comment by maartenba** [comment]
?$filter= + whatever OData query you want to do. E.g. a substring match on the package id:

?$filter=substringof('part',Id) eq true

**Comment by forki** [comment]
thx. @pms1969 please create issue on paket repo and I will flag it up-for-grabs.

**Comment by pms1969** [comment]
done.  Thanks

**Comment by forki** [comment]
there is initial support for custom v2 feeds now
