### ISSUE TITLE
Search should be case insensitive

### ISSUE THREAD

**Issue by dcorriveau-omniscient** [fsprojects/Paket.VisualStudio#93]
From the "Add Package" UI window, the search for packages should be case insensitive (like the nuget package manager).
![caseinsensitivesearch](https://cloud.githubusercontent.com/assets/11891420/12393087/7622240a-bdc1-11e5-98d9-a08e886da431.png)

**Comment by forki** [comment]
Mhm what source did you specify in dependencies file?

**Comment by dcorriveau-omniscient** [comment]
Nuget v3 API and a private server.

**Comment by forki** [comment]
What server? Our tests against nuget.org v3 are case insensitive

**Comment by dcorriveau-omniscient** [comment]
Seems like it's indeed case insensitive for https://api.nuget.org/v3/index.json but not for our private server. But if I use Nuget Package manager, the search is case insensitive for our private server, so I guess it has something to do with the Paket VS Extension and not the private nuget server ?

**Comment by forki** [comment]
Yes it probably is possible to fix in paket. That's why I asked which
server you use

https://github.com/fsprojects/Paket/blob/master/integrationtests/Paket.IntegrationTests/AutocompleteSpecs.fs#L29
you might want to modify this test locally to see what's going on.

**Comment by dcorriveau-omniscient** [comment]
Fixed.
