### ISSUE TITLE
Question: Check for Updates

### ISSUE THREAD

**Issue by mexx** [fsprojects/Paket.VisualStudio#94]
I'm curious, why the check for updates functionality includes pre-releases.
The output practically almost always deviates from `paket outdated` command, there is often a pre-release of some of the referenced packages present.

Btw. none of the update commands include pre-releases.
Can we make it consistent and also disallow pre-releases?

**Comment by forki** [comment]
There are switches for that. We might want to change the defaults. The current defaults were based on @agross' proposal

**Comment by mexx** [comment]
I didn't saw any switches in the code. It's simply hardcoded `true` in it, please see my referenced PR.

**Comment by forki** [comment]
Ah we are talking about the VS plugin. Sorry ;-) 

Yeah that might be fucked up.
